### ISSUE TITLE
text editor

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/BackNode#8]
use a rich text editor to edit texts

**Comment by JbIPS** [comment]
I tried, in vain, to use [Aloha 2](http://www.aloha-editor.org), but it looks like it's a bit too young. On the contrary, I tried [CKEditor](http://ckeditor.com/), with its inline edition, and it worked quite good! I just have some issue with the toolbar since Wysiwyg is preventing any click on it. Any idea @lexoyo ?

And I was wondering where in the new architecture should I include a library which is not on bower nor npm?

**Comment by RonanDrouglazet** [comment]
i think we don't need to use wysiwyg, just stage. Try to remove it for CKEditor ;) 

Wysiwyg are just an helper to select element on iframe, but CKEditor do it for us no ? 

to store CKEditor, two choice, use CKEditor as a submodule like in https://github.com/silexlabs/BackNode-prototype1 , build it (see https://github.com/ckeditor/ckeditor-dev) and copy files to static/external_lib/

or just copy your CKEditor files on static/external_lib/ and add it on GitHub project, simplier :) as you want ! it's better to use a submodule but not necessary usefull ^^

**Comment by lexoyo** [comment]
> Wysiwyg is preventing any click on it. Any idea @lexoyo ?

I will have a look
Did you push it to your branch?

> Wysiwyg are just an helper to select element on iframe, but CKEditor do it for us no ?

it has also several useful methods to add scripts and styles to the iframe but not save them

**Comment by JbIPS** [comment]
Just pushed it ([commit](https://github.com/JbIPS/BackNode/commit/d32cb24afe5322b342d1e6e72767d77e0f26ab04))!
Briefly, I added 2 scripts in package.json
```
"build:editor": "./submodules/ckeditor-dev/dev/builder/build.sh",
"copy:editor": "rsync -r ./submodules/ckeditor-dev/dev/builder/release/ckeditor ./static/external_lib",
```
but I didn't include them in `build:all` so it won't be regenerated every time (30s to build it) and `copy:templates` take care of the sync between static and dist. I'll be please to get feedback on this one so I keep staying in the right line here ;)
